apiVersion: v1
kind: Service
metadata:
  name: {{ include "actual-budget.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "actual-budget.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "actual-budget.selectorLabels" . | nindent 4 }}