apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helms.cubancodelab.net
      chart: pihole
      targetRevision: 0.1.1
      helm:
        valueFiles:
          - $values/infrastructure/pihole/values.yaml
    - repoURL: git@github.com:barbar0jav1er/homelab-argocd.git
      targetRevision: HEAD
      ref: values
    - repoURL: git@github.com:barbar0jav1er/homelab-argocd.git
      targetRevision: HEAD
      path: infrastructure/pihole/config
  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m