---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nordvpn-wireguard-key
  namespace: media
spec:
  encryptedData:
    private_key: AgCiTHK1ZnbZ4/mcmsUosfSzm6TE7/EqRfYElYrh8/h8Td1sOnZvJj6cUT/jXKMPloClXy33AJsUqrQLhAqT11e5VYILWIzgE+BcZ5UoKQu8cgYz6mr0ers/qQB1xKZqgEZ9h7naMpQlPOJ9sOxyNoFu4lOXatA1lvfTIXegolIizCr0IQ3niQp7f1+/cbdmL+abSpZS8amUBOxcHrHeZqG+CDc89vZ8XHgY6ppDvraQdQeB5lNUv3zksm8q4I5EShPw+f7K42jHz6y09W7XrgQQ8xNDTOoNAQH9UZWYX8oPLDZ/JcSDYrgUs8ZoNvt1g8XCxmq4FvRiQ1depxPTPMOwrc12R3CY5OqyE57/Wevx0ijMKsTUTCc7ZnqgLhdvVXibV0kI2GiLC95QQ9GrXF0oeSGq9yy43+2qmQIwJOAnF2aLGvrXz0kKfB6p+cetU4pjx6F0fjwMXq7KPrty1gV100CfIirv6c6NYkVb9mBOXL6yhoiFxC2I93cqMCikVZEbnCx/JOtdd5T1qVIfDnOV+xcMNpdNmBEuIg/SLOP1kFVkayG7HtRpDfdLSBhrSJHO4NUWnAycylhA/H6dXXfMIYvDK55e9JZYV07/WOPtLdDpfOsPUWVJ3NJNRacQbMEnb8IjqLrUjmUPNhGl4x54pG5U6p25P9ff1U4WJx1VB299AEV0IfcZZ4WUM+pcszObv4Uoo4bDHYMJ3La9UCg6BL0Nhw1icMIJ6wMXCSVQiy7T2idOErs8/85KcA==
  template:
    metadata:
      creationTimestamp: null
      name: nordvpn-wireguard-key
      namespace: media
