apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.9.1 # Replace with the Longhorn version you'd like to install or upgrade to
      helm:
        valueFiles:
          - $values/infrastructure/longhorn/values.yaml
    - repoURL: git@github.com:barbar0jav1er/homelab-argocd.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system