global:
  namespace: actual-budget

image:
  repository: actualbudget/actual-server
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5006

deployment:
  replicas: 1
  
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Persistent storage for budget data
persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 2Gi
  # Use hostPath for local storage (alternative to PVC)
  hostPath:
    enabled: true
    path: /opt/actual-budget

# Environment variables for multiuser support
env:
  # Default port (should match service.port)
  ACTUAL_PORT: "5006"
  # File upload limits
  ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB: "20"
  ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB: "50"
  ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB: "20"
  # Enable multiuser support - users can create accounts on login
  ACTUAL_USER_CREATION_MODE: "login"
  # Optional: Set login method (default allows creating users)
  ACTUAL_LOGIN_METHOD: "header"

# Ingress configuration
ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
  
  host: actual.v2.cubancodelab.net
  path: /
  pathType: Prefix
  
  tls:
    enabled: true
    secretName: actual-budget-tls