apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actual-budget
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helms.cubancodelab.net
      chart: actual-server
      targetRevision: 0.2.0
      helm:
        valueFiles:
          - $values/apps/actual-budget/values.yaml
    - repoURL: git@github.com:barbar0jav1er/homelab-argocd.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:barbar0jav1er/homelab-argocd.git
      targetRevision: HEAD
      path: apps/actual-budget/config
  destination:
    server: https://kubernetes.default.svc
    namespace: actual
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true