crds:
  enabled: true

rbac:
  create: true

controller:
  logLevel: info 

speaker:
  logLevel: info
  frr:
    enabled: false
  memberlist:
    enabled: true

prometheus:
  scrapeAnnotations: true
  podMonitor:
    enabled: false 
  serviceMonitor:
    enabled: false
  prometheusRule:
    enabled: false