---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-web-password
  namespace: pihole
spec:
  encryptedData:
    admin-password: AgAGyfF5nuywlXwuOoUWT7qX9uYV1bkAsKmdxOvXVFFOGckdFLVKeC0JRRDcwncGN4J4yCKIV+TRtURTLRl4ibHiMW+ua8Grr416DsNxeF5L1fROJlgtFLPbzdwSMc9buh3WygZ698O5/7I/YTLr8MRYquj2s2Bw07K7OUrClWQI6RWyc0PsKxiq27DJB3APNCOQM/8xe0FUzOPaGvqV2yXikwPmiJRyA11iIWO7b5bn2AbUw4daEb8Z7gDaMi+SoN4vkGdMZEffdy+Mwed3sHc5X3/+4u26++Avczk80BfBu/ByywiEFV5oRpGzlvUm0b4xlU/yk404mcKn81ewkma3H3aUnD7oL/E4PbquHU5ht4lbMxJ+yFQeC+rN0pT/Y+EiIcybmt1OHakPsqkJs904ynIl4cqmDk3CFn9++u+tRTRzUZXpWk9zim///Ab6LH3ov6s56IN/4vIUHZQB2oT0DClZGXpqT0zsj9IXGg6xhWstH2/41Q7Jnl0jQc32hJhjDnzvcthuzIlZ2BS7RHtT4hMjNCQqX8Qu6mzY04ruJ+yaN7FpHBdWLHmWT3rFMxcOD5JoOyW2u25XGdpB0zR/MJVDuWHtKNhm+lKzYbOJFs0SWT8jByJ+2spKzaveD6Bfs7KMijXhgKZqkHV8ypwOCVV4huS50fA50s9eOquk6kjZg6QrGSfVqVA9LeOLhRF1fQUGS4KnPmDnj8QhRw==
  template:
    metadata:
      creationTimestamp: null
      name: pihole-web-password
      namespace: pihole
