---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-web-password
  namespace: pihole
spec:
  encryptedData:
    password: AgAx1Ewu9YumsDmragALjj2/DSu6hIPhs6mwGyDj0OgXEJRtDna8yairPb1RgpKWYTjid4NlV5HRiSqOcrG/LZSJTW6fCQsD5XJIczPFMqUjJDoEXy8DA0KzR75hU1/n/wrlbcnolddW1xJlGJz3kTXwTo+DW65nxwjRq1LxWmY5OLrOY36oHqX+RVnu0c0JC10J4O2iPUK2En3nEVXmZhi2YmPq1pXXPpV4POUYmXKNELJ2c5SVK3zlpksNRpDWlp0EyvgdutH+UiSDpvt/KFH1MsM1gzcpG07dq7u/XY8x7Vb0U2zAah4HeNNHjzh38pUM52COuzPcs+IKRngFVtW9ziKjqev/nqrlTni+DsQMFuqobMTSe23Cz4uN3rtAqp8x31Nfvf8kAIfVZjw+w9e8yKTStwiW1hsVCtRZgsGJyo5GgEFawuMD8nr7ZEAydgoUy+2pE/XhCqvMslUgib8Y5WOtG9xvovS6bMeTCbvRagthvOQkUTQP5ubJL5i8jwFy0/fEqwVBawvuwv2FpVflAXxZvlY7Xp7hPnwR23WB+e9kkrOWCeluYiKbJg0LkVhbJ9AhnCf36yUHz2xmGUqad4zT9d4X33OcIOr/Z9P5MJKZjXN+UTHZTZ3SMjJBcvEfABWnlVqjfGWe+PZ6OaKx2J/GA29gArBFufF9D+w8UVq9Sqdx25dX+vGrd7fTNL7SrtHQMBOCbBCq
  template:
    metadata:
      creationTimestamp: null
      name: pihole-web-password
      namespace: pihole
