image:
  repository: pihole/pihole
  tag: "2025.08.0"

nameOverride: ""        
fullnameOverride: ""
commonLabels: {}
podLabels: {}

resources:  
  limits:
    cpu: 500m
    memory: 512Mi
  
  requests:
    cpu: 100m
    memory: 128Mi

serviceAccount:
  create: true
  name: ""
  annotations: {}

password:
  create: true
  value: "changeme123"
  existingSecret: ""
  existingSecretKey: "admin-password"

config:
  timezone: "Europe/Madrid"
  dnsUpstreams: "8.8.8.8;8.8.4.4;1.1.1.1"

services:
  dns:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: ""
  
  web:
    enabled: true
    type: ClusterIP
    port: 80

ingress:
  enabled: true 
  className: "traefik" 
  host: "pihole.local" 
  tls:
    enabled: true
    secretName: "pihole-tls"
  annotations: {}

persistence:
  config:
    enabled: true
    storageClass: ""
    size: "1Gi"
    accessModes:
      - ReadWriteOnce
    selector: {}
    annotations: {}
  
  dnsmasq:
    enabled: true
    storageClass: ""
    size: "500Mi"
    accessModes:
      - ReadWriteOnce
    selector: {}
    annotations: {}
  
