apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "media-stack.fullname" . }}-nfs-pv
spec:
  capacity:
    storage: {{ .Values.nfs.capacity }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}
  mountOptions:
    - nfsvers=4.1
    - hard
    - intr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "media-stack.fullname" . }}-nfs-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.global.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.nfs.capacity }}
  volumeName: {{ include "media-stack.fullname" . }}-nfs-pv