{{- if .Values.sonarr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "media-stack.fullname" . }}-sonarr
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "media-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "media-stack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: sonarr
  template:
    metadata:
      labels:
        {{- include "media-stack.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: sonarr
    spec:
      containers:
      - name: sonarr
        image: "{{ .Values.sonarr.image.repository }}:{{ .Values.sonarr.image.tag }}"
        ports:
        - containerPort: {{ .Values.sonarr.service.port }}
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "UTC"
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /media
        resources:
          {{- toYaml .Values.sonarr.resources | nindent 10 }}
      volumes:
      - name: config
        hostPath:
          path: /opt/media-stack/sonarr
          type: DirectoryOrCreate
      - name: media
        persistentVolumeClaim:
          claimName: {{ include "media-stack.fullname" . }}-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "media-stack.fullname" . }}-sonarr
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "media-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: sonarr
spec:
  type: {{ .Values.sonarr.service.type }}
  ports:
  - port: {{ .Values.sonarr.service.port }}
    targetPort: {{ .Values.sonarr.service.port }}
    protocol: TCP
    name: http
  selector:
    {{- include "media-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: sonarr
{{- end }}