apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-media-direct
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: nfs.csi.k8s.io
parameters:
  server: "10.2.0.20"
  share: "/volume2/media"
  mountPermissions: "0755"
volumeBindingMode: Immediate
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
  - hard
  - intr
  - rsize=1048576
  - wsize=1048576