apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-ssd-critical
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: false
