apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-hdd-bulk
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: nfs.csi.k8s.io
parameters:
  server: "10.2.0.20"
  share: "/volume2/k3s-hdd"
  mountPermissions: "0755"
volumeBindingMode: Immediate
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
  - hard
  - intr
  - rsize=1048576
  - wsize=1048576