apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: "65.7.0"
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/infrastructure/kube-prometheus-stack/values.yaml
    - repoURL: git@github.com:barbar0jav1er/homelab-argocd.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: kube-prometheus-stack-kube-state-metrics
      jsonPointers:
        - /spec/template/spec/containers/0/image
    - group: apps
      kind: Deployment
      name: kube-prometheus-stack-grafana
      jsonPointers:
        - /spec/template/spec/containers/0/image