---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBJrsDZN3W95DyaAH2x2BEBcmInrC/LUhJXs+nlUmkbrRDy+XaneBX39IKbWvhNnQfim26nV0VhtZKHMEHfSt5pMP4uW+nX67QfRYACueuZEciVQesRPS8tXNBv4AA1lNw9mKyCfBsWUD+LXybRe5sIySvflnb7EnwahDdRVzom/oDKrJdGYZpMl3emdk36U2QCHGBq5mwZc8lpmHIxm5AQ80yX102OtLVcWrYjU0B3xDyAJ3fuC9wzChVU1yRuHBPV0KmUt6NgFXmy3FpWlgQx5ytlQEa5V1DEifqEZcefPkPqhHOD2w/56XXtq87gLDVFW/BNMGE82QGtnbJ63R38d+LYHA3uRDTJ/7yR5xVdE/hOVNOaxUA3B0cCx7QvunYDWwK0eaaJ2y8PNElpUFOOiNE01PPPEGeyhPJeL8wRNeZtq0D+2FloFi6gMCfLD54kWG5ZpHJPEQJqkPMEI99CSSp73PM2tu5Jfz7a3Q6pduvbpdHGVcyJZmcT6y//tP520e5LWocrV767AY2VpgsS7VZuTp5tSXXFcTmJgTyCP87TvIMpAZwlzlVPMYyMeYVCzJeOr+L4wE1qtUN1sFUqbVp5EJL1JoXgqeHryOJMMImFP9RriTrDp0WvT/hEFQ9XKqqhF3aPFgAlQRYJIBTFhjm9JMLLH487sj77SaeiQWDmI8udVpH4QNsS6XdPdMvzLn6ShHuy12y59sTlPJui0aoznYRBedq8pp1Kgj9tHPIPWU3n98p0oAzwVA==
    admin-user: AgA7HZh7YuHb2+N1VPruaEXQ62THcD9fOaZJENUTwDUj9cxfKB9MpbQT2TbrmB8Fi4pu7PyL5JMeaiJRKyTou2nW8kJ5DDgwQ3Jz+ewdoUZ4KSyiZj6jEo/xNg0s6ot7/20xD0wfxRRzaPBe5Db2xO48XWdDlKruENmff0kG3c2a1Iz1MhvvKKgJtWIQ1IOqWOn75/MzxidTkevt3ROtjUYA1BUKOJVe/8RJZqNSMjKQdWtf9PT4pv4Q7qSVCU+oOj946zZmZ5VQrb25haoP/md7VS0bBym1SvDScQab42+ULupgkKhrWpdksn1vGNNu/dfj9DsO8T43knQXmYyDuyMd0/yFf0CAC/r83LPaEEmMxUch1pmNQ6c+O2FbPM6SWTBXfJ4tPXr4+FnqemEWYNVcJxCmZKiECsvsCOac8nn0ehgEJWTez42d9C6zlbFR9seoKWkFrVRsEARWOEYfaBco6huaKcreBAPnYO19EH6J7UvZwwl0qKvI0gRz7CXcCms5dwUwpXuAzHgBw39+08R/JbRrLtbiZ1ZeGfFwHBehqBi+A6iXf+nWJjOEHxOXa0Kik+LJTQy2MOMPlzJg7Ddwt8ZPP1salQp0Th4faWz8iZ1qcmJplv9PNSRiC2KcV/fbTIKgbMJ2Oqwv0lksXRCYwVWMOqtgkspBL+zvx0c4bAaln1jCc8RcwGUaM06n8r59hpjPpg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring