{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "homelab-app.fullname" . }}
  labels:
    {{- include "homelab-app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.app.name }}.{{ .Values.ingress.domain }}
      secretName: {{ .Values.app.name }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.app.name }}.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "homelab-app.fullname" . }}
                port:
                  number: {{ .Values.app.service.port }}
{{- end }}