---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Deploy before ClusterIssuers
spec:
  encryptedData:
    api-token: AgCh0pTqLuNbM6o/e9wyhlbXd4LHqRYr3OmPhG5sBG5msjvSdYQf96dC2+Ym6oLwEo230OBStU9m+pfShGGzMsOxQxwuxTDzPA3EUXqZaJEtXXfCPutLmNi5kBs37k5wMe0ctN0wvpQT8ehigAxhFGWt2rWh9wvQxm48AFjMP4CmzgCmnaclkWIE8jW2sUmgJy+S4oiih3+r4Vv72Igo1aEQ2Grnd5HPqqp8VO26TLYoKX9jKFnBMZhUZxOoHwdsUIC/LPAIf9fVIsRva03NpTOXrPvHDDYf7prI/1rcgRwfMM0sBE9lX+e+czcFGbRsQlQYSPpqMsjKr3afNXUW304SsslEcLUeWxGfOvP7zNSkrsGRfN1HD7kji1om867H9pqxRID713GUSjFfkxR3m1fAvYAG6iRVhF3hztKYXoVzweLK0oXs6ZA3YwHnKoCUd67/Klkgw3cmrbZRS6CKA3Sjc1fDfgllNf113tuAKnRvZr895dDhVoOp/ULJL+7UJW6PyFp2LrCn6baP1qZTIkhCSQYgr/c5kamPq/BumHSYkzZE47isG36bwaa+F/VWn+ZMrV80c/mvcepAmaX6EnWIs8RuOO8lf5bIc9rlV9bj8403nvC5qKCQO57JxEQh2HCvwwYOLPpd5qI8gIerjAgCU6G89kebR8n8v8Vgnw9mEiXTBnc0eSUc9P/+A5pQ1c9qrsFfTESZxfxnWjBv7aIy815XRY3clBZqxfRQPOTXeKb3rGh6B5Ln
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager